branch-defaults:
  Dockerize:
    environment: votablyrails-prod-env
global:
  application_name: votably-rails
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Docker 1.11.1
  default_region: us-east-1
  profile: eb-cli
  sc: git
