development:
  adapter: postgresql
  encoding: unicode
  database: votably
  pool: 5
  username: jeffmason
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: votably_test
  pool: 5
  username: jeffmason
  password: 

production:
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV['DB_POOL'] || 5 %>